/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Field: typeof import('./../components/form/Field.vue')['default']
    FileUpload: typeof import('./../components/form/FileUpload.vue')['default']
    FormError: typeof import('./../components/form/FormError.vue')['default']
    FormLabel: typeof import('./../components/form/FormLabel.vue')['default']
    FormTip: typeof import('./../components/form/FormTip.vue')['default']
    HeroiconsChevronUp: typeof import('~icons/heroicons/chevron-up')['default']
    HeroiconsCloudArrowUp: typeof import('~icons/heroicons/cloud-arrow-up')['default']
    HeroiconsCog6Tooth: typeof import('~icons/heroicons/cog6-tooth')['default']
    HeroiconsDocumentText: typeof import('~icons/heroicons/document-text')['default']
    HeroiconsHome: typeof import('~icons/heroicons/home')['default']
    HeroiconsMusicalNote: typeof import('~icons/heroicons/musical-note')['default']
    HeroiconsPlayCircle: typeof import('~icons/heroicons/play-circle')['default']
    HeroiconsTrash: typeof import('~icons/heroicons/trash')['default']
    HeroiconsUserGroup: typeof import('~icons/heroicons/user-group')['default']
    HeroiconsXMark: typeof import('~icons/heroicons/x-mark')['default']
    ImageUpload: typeof import('./../components/form/ImageUpload.vue')['default']
    Layout: typeof import('./../layouts/Layout.vue')['default']
    Link: typeof import('@inertiajs/vue3')['Link']
    MdiClose: typeof import('~icons/mdi/close')['default']
    MediaPlaceholder: typeof import('./../components/player/MediaPlaceholder.vue')['default']
    Modal: typeof import('./../components/modals/Modal.vue')['default']
    Pagination: typeof import('./../components/general/Pagination.vue')['default']
    Player: typeof import('./../components/player/Player.vue')['default']
    Playlist: typeof import('./../components/player/Playlist.vue')['default']
    RadioGroup: typeof import('@headlessui/vue')['RadioGroup']
    RadioGroupLabel: typeof import('@headlessui/vue')['RadioGroupLabel']
    RadioGroupOption: typeof import('@headlessui/vue')['RadioGroupOption']
    RoomMembers: typeof import('./../components/room/RoomMembers.vue')['default']
    RoomNavbar: typeof import('./../components/room/RoomNavbar.vue')['default']
    RoomNavbarButton: typeof import('./../components/room/RoomNavbarButton.vue')['default']
    RoomUploadMediaModal: typeof import('./../components/room/RoomUploadMediaModal.vue')['default']
    Select: typeof import('./../components/form/Select.vue')['default']
    SelectModel: typeof import('./../components/form/SelectModel.vue')['default']
    Switch: typeof import('./../components/form/Switch.vue')['default']
    SwitchField: typeof import('./../components/form/SwitchField.vue')['default']
    SwitchGroup: typeof import('@headlessui/vue')['SwitchGroup']
    TextareaInput: typeof import('./../components/form/TextareaInput.vue')['default']
    TextInput: typeof import('./../components/form/TextInput.vue')['default']
  }
}
